[package]
name = "Teleop"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
zenoh = "1.3.4"
tokio = { version = "1.45.0", features = ["full"] }
kuksa-rust-sdk = "0.1.2"